pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Machines/ElectricBlockBreaker.java, src/main/java/ne/fnfal113/fnamplifications/MaterialGenerators/Methods/CustomMaterialGenerator.java, src/main/java/ne/fnfal113/fnamplifications/PowerGenerators/PowahGenerator.java, src/main/resources/config.yml
Added Block Breaker
To be determined once players have found issues
=> Added Electric Block breaker

pom.xml, src/main/java/ne/fnfal113/fnamplifications/Machines/ElectricBlockBreaker.java
Fix Budding Amethyst dropping which should not be happening
TBD
=> Fixed Budding Amethyst dropping

pom.xml, src/main/java/ne/fnfal113/fnamplifications/Machines/ElectricBlockBreaker.java
Changed the various maps into a single cache class
Moved elements into a new BlockMenuPreset#onNewInstance
Removed a lot from the tick (more can be done here btw!)
Removed door and bed method in favour of tags
#hasViewer
I only did like 2 mins of testing - not enough time for a proper test - make sure you're happy with this before moving it into prod :)
todo: Remove slimefun items
Think about removing the sound. Sounds are cool but per-tick they are heavy
=> Less laggy

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Machines/ElectricBlockBreaker.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/Listeners/MysteryStickListener.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick2.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick3.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick4.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick5.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick6.java, src/main/resources/config.yml
- Re-added block breaker (vanilla blocks only)
- Added new Mysterious Stick 
TBD
=> Added Block Breaker (Vanilla) and Mystery Sticks

pom.xml, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/Listeners/MysteryStickListener.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick7.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick8.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick9.java
- Added Mystery Sticks VII, VIII, IX 
TBD
=> Added 3 new mystery sticks

pom.xml, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Items/FnItemRecipes.java, src/main/java/ne/fnfal113/fnamplifications/MaterialGenerators/FNMaterialGenerators.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/Listeners/MysteryStickListener.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick10.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick2.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick4.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick5.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick7.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick8.java, src/main/java/ne/fnfal113/fnamplifications/MysteriousItems/MysteryStick9.java, src/main/java/ne/fnfal113/fnamplifications/PowerGenerators/FNSolarGenerators.java, src/main/java/ne/fnfal113/fnamplifications/PowerGenerators/PowahGenerator.java
- Added Mystery Stick X
- Buffed xp level requirements for the mysterious sticks
- Chores
=> Added Mystery Stick X

pom.xml, src/main/java/ne/fnfal113/fnamplifications/Gears/FnLeggings.java, src/main/java/ne/fnfal113/fnamplifications/Gears/Listeners/GearListener.java
- Gears balancing and small fix
TBD
=> Gears balancing and small fix

pom.xml, src/main/java/ne/fnfal113/fnamplifications/Machines/ElectricMachineDowngrader.java
- Nerfed metal scrap mass automation
=> Metal Scraps balancing

pom.xml, src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfInvisibility.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfLocomotion.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfTeleportation.java
- Added Staff of Teleportation, Locomotion and Invisibility
- To be determined
=> Added new 3 staffs

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/Listener/QuiverListener.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/Quiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/SpectralQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/UpgradedQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/UpgradedSpectralQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfDeepFreeze.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfHellFire.java, src/main/resources/config.yml
- Added Staff of Hellfire and Deep-freeze (Max uses configurable also in config.yml)
- Quivers fixes
- TBD
=> Added 2 new Staffs and fixes

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfConfusion.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfDeepFreeze.java, src/main/resources/config.yml
- Staffs area of effect improvements (much better effect apply)
- Added Staff of Confusion
=> Staff improvements and added staff of confusion

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfGravitationalPull.java, src/main/resources/config.yml
- Added new Staff of Gravitational Pull
- Staff of confusion faster effect apply
- TBD
=> Added Staff of Gravitational Pull

pom.xml, src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java, src/main/java/ne/fnfal113/fnamplifications/Gears/FnChestPlate.java, src/main/java/ne/fnfal113/fnamplifications/Gears/Listeners/GearListener.java, src/main/java/ne/fnfal113/fnamplifications/Gears/Runnables/ArmorEquipRunnable.java, src/main/resources/config.yml
- FN's Gears of Friction balancing
- 1 bonus effect for FN Gear Chestplate when level 30 is reach, applies when worn
=> Gears of Friction Balancing

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/Quiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/SpectralQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/UpgradedQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/UpgradedSpectralQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfAwareness.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfMinerals.java, src/main/resources/config.yml
- Added staff of mineral and staff of awareness
- Increased quiver capacity to store more arrows, additional 64 and 92 capacity
=> Added staff of mineral and awareness

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfFangs.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfSkulls.java, src/main/resources/config.yml
- Added Staff of Fangs and Staff of Skulls
=> Added Staff of Fangs and Staff of Skulls

pom.xml, src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Tools/FnHoe.java, src/main/java/ne/fnfal113/fnamplifications/Tools/Listener/HoeListener.java
=> Added FN's Hoe

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfAirStrider.java, src/main/resources/config.yml
=> Added Staff of Air Strider

pom.xml, src/main/java/ne/fnfal113/fnamplifications/ConfigValues/ReturnConfValue.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItemSetup.java, src/main/java/ne/fnfal113/fnamplifications/Items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/UpgradedQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/Listener/StaffListener.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfAirStrider.java, src/main/java/ne/fnfal113/fnamplifications/Staffs/StaffOfWebs.java, src/main/java/ne/fnfal113/fnamplifications/Tools/FnHoeAutoPlant.java, src/main/java/ne/fnfal113/fnamplifications/Tools/Listener/HoeListener.java, src/main/resources/config.yml
- Added staff of cobwebs
- Added FN's reseeding hoe
- Upgraded Quiver recipe fix
=> Added Staff of Cobweb and fixes

pom.xml, src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java, src/main/java/ne/fnfal113/fnamplifications/Gears/Commands/CheckProgress.java, src/main/java/ne/fnfal113/fnamplifications/Gears/FnBoots.java, src/main/java/ne/fnfal113/fnamplifications/Gears/FnChestPlate.java, src/main/java/ne/fnfal113/fnamplifications/Gears/FnHelmet.java, src/main/java/ne/fnfal113/fnamplifications/Gears/FnLeggings.java, src/main/java/ne/fnfal113/fnamplifications/Gears/Listeners/GearListener.java, src/main/java/ne/fnfal113/fnamplifications/Gears/MainGears.java, src/main/java/ne/fnfal113/fnamplifications/Gems/Implementation/Gem.java, src/main/java/ne/fnfal113/fnamplifications/Multiblock/FnAssemblyStation.java, src/main/java/ne/fnfal113/fnamplifications/Multiblock/FnGemAltar.java, src/main/java/ne/fnfal113/fnamplifications/Multiblock/FnMysteryStickAltar.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/Interface/QuiverImpl.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/Listener/QuiverListener.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/MainQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/Quiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/SpectralQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/UpgradedQuiver.java, src/main/java/ne/fnfal113/fnamplifications/Quiver/UpgradedSpectralQuiver.java, src/main/resources/plugin.yml
- Added command to check FN Gear progress (/fngear)
- Allow multi-blocks to output even with or without output chest
- Rewritten the code for Gears and Quiver
=> Fixes and code rewrites

pom.xml, src/main/java/ne/fnfal113/fnamplifications/machines/ElectricJukebox.java, src/main/java/ne/fnfal113/fnamplifications/machines/abstracts/AbstractJukeBox.java, src/main/java/ne/fnfal113/fnamplifications/machines/implementation/JukeBox.java, src/main/java/ne/fnfal113/fnamplifications/machines/implementation/RegisterMachines.java
- A little code refactor for jukebox
=> A little refactor for jukebox

pom.xml, src/main/java/ne/fnfal113/fnamplifications/machines/implementation/JukeBox.java, src/main/java/ne/fnfal113/fnamplifications/tools/BlockRotator.java, src/main/java/ne/fnfal113/fnamplifications/utils/PlayerJoinLister.java
- Fix small bug with block rotator
=> Fix block rotator small bug

src/main/java/ne/fnfal113/fnamplifications/gems/BlindBindGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/DisruptedGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/GuardianGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/HastyGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/abstracts/AbstractGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/events/GuardianSpawnEvent.java, src/main/java/ne/fnfal113/fnamplifications/gems/handlers/GemHandler.java, src/main/java/ne/fnfal113/fnamplifications/gems/handlers/OnArrowHitHandler.java, src/main/java/ne/fnfal113/fnamplifications/gems/handlers/OnBlockBreakHandler.java, src/main/java/ne/fnfal113/fnamplifications/gems/handlers/OnDamageHandler.java, src/main/java/ne/fnfal113/fnamplifications/gems/handlers/OnGuardianSpawnHandler.java, src/main/java/ne/fnfal113/fnamplifications/gems/handlers/OnRightClickHandler.java, src/main/java/ne/fnfal113/fnamplifications/gems/implementation/GuardianTask.java, src/main/java/ne/fnfal113/fnamplifications/gems/implementation/RegisterGems.java, src/main/java/ne/fnfal113/fnamplifications/gems/listener/GemListener.java, src/main/java/ne/fnfal113/fnamplifications/items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/utils/PlayerJoinLister.java
- Added Disrupted Gem
- Fixed 1.16.5 noSuchField error with Blindbind gem
- Little code rewrite on Gem Handling (Dev side)
- Added GuardianSpawnEvent (API for devs)
- Small code chores and cleanups
- To be determined if any exist soon
=> New gem and handling

pom.xml, src/main/java/ne/fnfal113/fnamplifications/gems/LootGem.java
- Fix hardcoded chance of loot gem
=> Fix hardcoded chance for loot gem

pom.xml, src/main/java/ne/fnfal113/fnamplifications/gems/ShockwaveGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/abstracts/AbstractGemUnbinder.java, src/main/java/ne/fnfal113/fnamplifications/gems/implementation/GemUnbinderTask.java, src/main/java/ne/fnfal113/fnamplifications/gems/listener/GemListener.java, src/main/java/ne/fnfal113/fnamplifications/gems/listener/GemUnbinderListener.java, src/main/java/ne/fnfal113/fnamplifications/gems/unbinder/BlemishedUnbindGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/unbinder/DamagedUnbindGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/unbinder/FlawlessUnbindGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/unbinder/PreciousUnbindGem.java
- refactored gem unbinder (high and lower level classes)
- code chores
=> micro refactors

.github/workflows/blob-builds.yml, .gitignore, README.md, pom.xml, src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java, src/main/java/ne/fnfal113/fnamplifications/gems/TelepathyGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/implementation/Gem.java, src/main/java/ne/fnfal113/fnamplifications/gems/implementation/UpgradedGem.java, src/main/java/ne/fnfal113/fnamplifications/gems/listener/GemListener.java, src/main/java/ne/fnfal113/fnamplifications/items/FNAmpItems.java, src/main/java/ne/fnfal113/fnamplifications/staffs/StaffOfMinerals.java, src/main/java/ne/fnfal113/fnamplifications/tools/ThrowableTorch.java, src/main/java/ne/fnfal113/fnamplifications/tools/implementation/ThrowableItemTask.java
- resolves #111 and #110
- fix throwable torch "cannot drop air", possibly the item might be despawned before executing #dropItemNaturally.
- add telepathy support for hoes and shovels
- use ```BlobBuildsUpdater``` class instead of ```GithubBuildsUpdater``` through dough-updater dependency instead of updating slimefun dep.
=> bug fixes and telepathy suggestion added

pom.xml, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick10.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick11.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick2.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick3.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick4.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick5.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick6.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick7.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick8.java, src/main/java/ne/fnfal113/fnamplifications/mysteriousitems/MysteryStick9.java
=> fixed mystery sticks unchecked cast
